apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deployment-fromtf
spec:
  selector:
    matchLabels:
      app: kubeadmfromtf
  
  template:
    metadata:
      labels:
        app: kubeadmfromtf
    spec:
      containers:
      - name: fromtf-ctr
        image: kishorsg/my-app:2.0.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fromtf-svc
  labels:
    app: kubeadmfromtf
spec:
  type: NodePort
  ports:
    - port: 8075
      targetPort: 8080
      protocol: TCP   
      
  selector:
    app: kubeadmfromtf
